services:
  squirtle-main:
    build:
      context: .
      dockerfile: Dockerfile
    image: squirtle-squad-browser:latest

  python-pdf-service:
    build:
      context: ./python-pdf-service
      dockerfile: Dockerfile
    image: squirtle-python-pdf-browser:latest
