
services:
  # Python PDF Service
  python-pdf-service:
    image: ghcr.io/hackrx-6/squirtle-squad-python-pdf:latest
    container_name: squirtle-python-pdf
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    networks:
      - squirtle-network

  # Main Application
  squirtle-main:
    image: ghcr.io/hackrx-6/squirtle-squad:latest
    container_name: squirtle-main
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PDF_SERVICE_URL=http://squirtle-python-pdf:8000
      - USE_PYTHON_PDF=true
      
      # Embeddings Configuration
      - EMBEDDINGS_MODEL_API_KEY=${EMBEDDINGS_MODEL_API_KEY}
      - EMBEDDINGS_MODEL_ENDPOINT=${EMBEDDINGS_MODEL_ENDPOINT}
      - EMBEDDINGS_MODEL_DEPLOYMENT_NAME=${EMBEDDINGS_MODEL_DEPLOYMENT_NAME}
      - EMBEDDINGS_MODEL_API_VERSION=${EMBEDDINGS_MODEL_API_VERSION}
      - EMBEDDINGS_MODEL_API_KEY_2=${EMBEDDINGS_MODEL_API_KEY_2}
      - EMBEDDINGS_MODEL_ENDPOINT_2=${EMBEDDINGS_MODEL_ENDPOINT_2}
      - EMBEDDINGS_MODEL_DEPLOYMENT_NAME_2=${EMBEDDINGS_MODEL_DEPLOYMENT_NAME_2}
      - EMBEDDINGS_MODEL_API_VERSION_2=${EMBEDDINGS_MODEL_API_VERSION_2}
      
      # LLM Configuration
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_BASE_URL=${LLM_BASE_URL}
      - LLM_DEPLOYMENT_NAME=${LLM_DEPLOYMENT_NAME}
      - LLM_MODEL=${LLM_MODEL}
      - LLM_SERVICE=${LLM_SERVICE}
      - LLM_API_VERSION=${LLM_API_VERSION}
      - LLM_API_KEY_2=${LLM_API_KEY_2}
      - LLM_BASE_URL_2=${LLM_BASE_URL_2}
      - LLM_DEPLOYMENT_NAME_2=${LLM_DEPLOYMENT_NAME_2}
      - LLM_MODEL_2=${LLM_MODEL_2}
      - LLM_SERVICE_2=${LLM_SERVICE_2}
      - LLM_API_VERSION_2=${LLM_API_VERSION_2}
      
      # Other Configuration
      - HACKRX_AUTH_TOKEN=${HACKRX_AUTH_TOKEN}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT}
      - SENTRY_RELEASE=${SENTRY_RELEASE}
      - SENTRY_TRACES_SAMPLE_RATE=${SENTRY_TRACES_SAMPLE_RATE}
      - SENTRY_ENABLE_TRACING=${SENTRY_ENABLE_TRACING}
    
    volumes:
      - /var/log/squirtle-squad:/app/logs
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    depends_on:
      python-pdf-service:
        condition: service_healthy
    networks:
      - squirtle-network

networks:
  squirtle-network:
    driver: bridge
